### ISSUE TITLE
Dropdown de programas

### ISSUE THREAD

**Issue by fakel** [Laboratoria/laboratoria-plus-ce-header#1]
Con el incremento de la cantidad de programas de L+ es necesario actualizar el header component para incluir un dropdown, los diseños se pueden ver abajo.

Deadline: Es necesario salir la semana del 22 de Mayo

Solicitud de: (slack) @mila

![image](https://github.com/Laboratoria/laboratoria-plus-ce-header/assets/10450905/b9f9fcef-95ec-475d-9e28-e9490bb0fff3)

![image](https://github.com/Laboratoria/laboratoria-plus-ce-header/assets/10450905/26a2c09e-83b9-46e2-afbf-a7f463f7f1e6)

**Comment by fakel** [comment]
Los últimos cambios realizados fueron publicados en npm con la versión v1.0.1 e integrados a las siguientes páginas de instapage en vista previa:

![image](https://github.com/Laboratoria/laboratoria-plus-ce-header/assets/10450905/d36dcf66-208e-4e3b-b2a0-a35f7f633f3f)

Quedamos a la espera de la validación y aceptación

**Comment by lupomontero** [comment]
Marcado como resuelto en https://github.com/Laboratoria/next/issues/131#issuecomment-1572772437
