### ISSUE TITLE
Inclusión de programas nuevos en el header

### ISSUE THREAD

**Issue by fakel** [Laboratoria/laboratoria-plus-ce-header#2]
Contexto

Mila: 

> 
> Vamos a crear 2 páginas más para 2 programas nuevos.
> 
> Los programas nuevos son:
> 
> - Comunicación Efectiva
> - Toma de Decisiones Basadas en Datos

![image](https://github.com/Laboratoria/laboratoria-plus-ce-header/assets/10450905/0fa338ef-576d-440e-b07c-ad26f922c1a8)

Petición: Actualizar header con los programas nuevos en instapage

**Comment by lupomontero** [comment]
@fakel, este issue está abirto desde julio... lo podemos considerar ya como cerrado?
